server:
  port: 8080
  servlet:
    context-path: /ljf

spring:
  datasource:
    url: jdbc:mysql://10.1.65.12:3306/hello?useUnicode=true&useSSL=false&characterEncoding=utf8";
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root